<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Meta.Dow.Administration</RootNamespace>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <UserSecretsId>Meta.Dow.Administration-c2d31439-b723-48e2-b061-5ebd7aeb6010</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..</DockerfileContext>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\shared\Meta.Dow.Microservice.Shared\Meta.Dow.Microservice.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\shared\Meta.Dow.ServiceDefaults\Meta.Dow.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\identity\src\Meta.Dow.IdentityService.Application.Contracts\Meta.Dow.IdentityService.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\identity\src\Meta.Dow.IdentityService.MongoDB\Meta.Dow.IdentityService.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\saas\src\Meta.Dow.SaaS.Application.Contracts\Meta.Dow.SaaS.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Meta.Dow.Administration.HttpApi\Meta.Dow.Administration.HttpApi.csproj" />
    <ProjectReference Include="..\..\src\Meta.Dow.Administration.Application\Meta.Dow.Administration.Application.csproj" />
    <ProjectReference Include="..\..\src\Meta.Dow.Administration.MongoDB\Meta.Dow.Administration.MongoDB.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>
</Project>
