<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Meta.Dow.IdentityService</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Account.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.AutoMapper" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="10.6.0" />
    <ProjectReference Include="..\Meta.Dow.IdentityService.Application.Contracts\Meta.Dow.IdentityService.Application.Contracts.csproj" />
    <ProjectReference Include="..\Meta.Dow.IdentityService.Domain\Meta.Dow.IdentityService.Domain.csproj" />
  </ItemGroup>
</Project>
